[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_voting = "bdxoveDPX8CmkVw5MLLvCvrCddXb78TZztrWffnHN3e"

[registry]
url = "https://api.apr.dev"

[provider]

wallet = "~/.config/solana/id.json"

cluster = "http://127.0.0.1:8898"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


